BitsPlease/BitsPlease/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^nimda/', admin.site.urls),
    url(r'^', include("contest.urls"), name="contest")
]

BitsPlease/contest/urls.py
from django.conf.urls import url
from .views import (
    QuestionListView,
    ProblemDetailView,
    ContestListView,
    ContestDetailView,
    AboutUs,
    ContactUs,
    NoticeListView,
)

urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name="problems"),
    url(r'aboutus/', AboutUs.as_view(), name="aboutus"),
    url(r'notice/', NoticeListView.as_view(), name="notice"),
    url(r'contactus/', ContactUs.as_view(), name="contactus"),
    url(r'^problem/(?P<pk>\d+)', ProblemDetailView.as_view(), name="problem_detail"),
    url(r'^contest/$', ContestListView.as_view(), name="contests"),
    url(r'^contest/(?P<pk>\d+)', ContestDetailView.as_view(), name="contest_detail"),


]

BitsPlease/contest/models.py
from django.db import models
from django.urls import reverse

LEVEL_CHOICES = (
    ('beginner', "Beginner"),
    ('easy', "Easy"),
    ('medium', "Medium"),
    ('hard', "Hard")
)

DIVISION_CHOICES = (
    ('div1', "Div 1"),
    ('div2', "Div 2")
)


class Notice(models.Model):
    title = models.TextField()
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    publish = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Contest(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    division = models.CharField(max_length=20, choices=DIVISION_CHOICES)
    winners = models.TextField(blank=True, default=None)
    publish = models.BooleanField(default=False)
    contest_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("contest:contest_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Question(models.Model):
    contest = models.ForeignKey('contest.Contest', blank=True, null=True, related_name='questions')
    tag = models.ForeignKey(Tag, blank=True, null=True, related_name='problems')
    name = models.CharField(max_length=200)
    description = models.TextField()
    testcases = models.TextField(null=True, blank=True, default=None)
    level = models.CharField(max_length=50, choices=LEVEL_CHOICES)
    publish = models.BooleanField(default=False)
    Url1 = models.URLField(max_length=500, null=True, blank=True, default=None)
    Url2 = models.URLField(max_length=500, null=True, blank=True, default=None)
    Url3 = models.URLField(max_length=500, null=True, blank=True, default=None)
    Url4 = models.URLField(max_length=500, null=True, blank=True, default=None)
    Url5 = models.URLField(max_length=500, null=True, blank=True, default=None)
    answer = models.URLField(max_length=500, blank=True, default=None)
    add_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("contest:problem_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

BitsPlease/contest/views.py
from django.views.generic import ListView, DetailView, View, TemplateView
from .models import Question, Contest, Tag, Notice
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.db.models import Q


class NoticeListView(ListView):
    model = Notice
    template_name = "notice_list.html"

    def get_queryset(self):
        queryset = Notice.objects.all().order_by("-date")
        queryset = queryset.filter(publish=True)

        return queryset


class AboutUs(TemplateView):
    template_name = "aboutus.html"


class ContactUs(TemplateView):
    template_name = "contactus.html"


class ContestDetailView(DetailView):
    model = Contest
    template_name = "contest_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ContestDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        obj = get_object_or_404(Contest, pk=pk)
        if obj.publish is False:
            raise Http404

        context['object'] = obj
        return context


class ContestListView(ListView):
    model = Contest
    template_name = "contest_list.html"

    def get_queryset(self):
        queryset = Contest.objects.all().order_by('-contest_date')
        queryset = queryset.filter(publish=True)
        div = self.request.GET.get('div' or None)

        if div:
            div = div.replace(" ", "").lower()
            queryset = queryset.filter(division__iexact=div)

        return queryset


class ProblemDetailView(DetailView):
    model = Question
    template_name = "question_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProblemDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        obj = get_object_or_404(Question, pk=pk)

        if not obj.publish:
            raise Http404

        context['object'] = obj
        return context


class QuestionListView(ListView):
    model = Question
    template_name = "question_list.html"

    def get_context_data(self, **kwargs):
        context = super(QuestionListView, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        queryset = Question.objects.filter(publish=True)
        level = self.request.GET.get('level' or None)
        tag = self.request.GET.get('tag' or None)
        qry = self.request.GET.get('qry' or None)

        if qry:
            queryset = queryset.filter(
                Q(name__icontains=qry) |
                Q(description__icontains=qry)
            ).distinct()

        if tag:
            queryset = queryset.filter(tag__name__iexact=tag)

        if level:
            queryset = queryset.filter(level__iexact=level)

        queryset = queryset.order_by("-id")

        return queryset

BitsPlease/templates/aboutus.html
{% extends "base.html" %}

{% block content %}
	<br>
    <div class="jumbotron">
        <h1>About us</h1>
    	<br>
    	<p>
    	    Are you a code enthusiast looking for reasons to code?
            Welcome to Bitsplease!!!!
            We at Bitsplease provide you an opportunity to showcase and improve your coding skills.
            From beginners to masters we have got a challenge for everyone.
            Take part in multiple contest and display your coding capabilities, interact with us to learn and discuss various coding techniques to tackle logical problems.
            Happy Coding!!!



    	</p>
    	<ul>Why bitsplease?
                <li>Provides a platform for code skill development</li>
                <li>Regular Contest to sharpen your code mind</li>
                <li>Variety in questions asked, developing logical reasoning Foundation</li>
            </ul>
    	<p>
    	     <a href="https://bitsplease.pythonanywhere.com">bitsplease.pythonanywhere.com</a> is the official website for the Bitsplease Technical Society of Maharaja Surajmal Institute, Janak Puri, New Delhi.
            Founded by students of the institute, it's focused on providing a stage for code enthusiasts to practice skills and serve as platform of discussion for coding related environments.

    	</p>
    </div>
{% endblock content %}

BitsPlease/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>BitsPlease</title>
  <link rel="icon" href="https://i.imgur.com/4BLSIya.png" type="image/gif" sizes="16x16">
</head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />


<body>

<nav class="navbar navbar-inverse bg-inverse navbar-toggleable-md">
      <div class="container">
        <a class="navbar-brand" href="{% url 'problems' %}">
          <img src="https://i.imgur.com/qpAfJHT.png" width="220" height="35" class="d-inline-block align-top" alt="">
      </a>
        <button class="navbar-toggler  pull-right" type="button" data-toggle="collapse" data-target="#navbarsExampleContainer" aria-controls="navbarsExampleContainer" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarsExampleContainer">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contests' %}">Contest <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <form class="form-inline my-md-0" method="get" action="{% url 'problems' %}">
              <input class="form-control mr-sm-2" type="text"name='qry' placeholder="Search Keyword">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a  class="nav-link" href="{% url 'notice' %}">Notice</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'aboutus' %}">About us</a>
            </li>
            <li class="nav-item active">
              <a  class="nav-link" href="{% url 'contactus' %}">Contact us</a>
            </li>
          </ul>
        </div>

      </div>
    </nav>

<div class="container">
{% block content %}
{% endblock content %}
</div>
<!-- Start of StatCounter Code for Tumblr -->
<script type="text/javascript">
//<![CDATA[
var sc_project=11449464;
var sc_invisible=1;
var sc_security="a0d5d6d3";
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter_xhtml.js'></"+"script>");
//]]>
</script>
<noscript><div class="statcounter"><a title="hit counter"
href="http://statcounter.com/" class="statcounter"><img
class="statcounter"
src="//c.statcounter.com/11449464/0/a0d5d6d3/1/" alt="hit
counter" /></a></div></noscript>
<!-- End of StatCounter Code for Tumblr -->

</body>
</html>

BitsPlease/templates/contactus.html
{% extends "base.html" %}

{% block content %}
    <br>
    <div class="jumbotron">
            <h1>Contact Us</h1>
            <br><br>
            <h5>Got queries or doubts?</h5>
            <h5>Ask us at: <a href="mailto:bitspleasemsi@gmail.com?Subject=Hello" target="_top">bitspleasemsi@gmail.com</a></h5>
            <h5>Contribute to our GitHub repository <a href="https://github.com/BitsPleaseMSI/BitsPlease-solutions">here</a></h5>
    </div>

{% endblock content %}

BitsPlease/templates/contest_detail.html
{% extends "base.html" %}

{% block content %}
	<br>
	<div class="jumbotron">
		<h2>{{ object.id }}.{{ object.name }}</h2>
		<p> {{ object.division }} | {{ object.contest_date }}</p>
		<hr>
		<p>{{ object.description|linebreaks }}</p>
		<h4>Problems</h4>
		<table class="table table-bordered">
		  <thead class="thead-inverse">
		    <tr>
		      <th>Id</th>
		      <th>Title</th>
		      <th>Difficulty</th>
		    </tr>
		  </thead>
		  <tbody>
		  {% for obj in object.questions.all %}
		    <tr>
	    	<th>{{ obj.id }}</th>
	    	<th><a href="{% url 'problem_detail' pk=obj.id %}">{{ obj.name }}</a></th>
	    	<th>{{ obj.get_level_display }}</th>

		    </tr>
		    {% empty %}
		    <th>No results</th>
		   {% endfor %}
		  </tbody>
		</table>

		<div class="container">
			{% if object.winners|length > 0 %}
				<h4>Winners</h4>
				<p>{{ object.winners|safe|linebreaks }}</p>
			{% endif %}
		</div>
	</div>

{% endblock content %}

BitsPlease/templates/contest_list.html
{% extends "base.html" %}

{% block content %}
<br>
<h1>Contests</h1>
<br>

<form class="form-inline" method="get">
	<div class="form-group">
	    <select class="form-control" style="width:260px;" name="div">
	    <option disabled selected value> Div </option>
	    	<option>Div 1</option>
	    	<option>Div 2</option>
	    </select>
  	</div>
  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button type="submit" class="btn btn-success">Filter</button>
</form>
<br>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Division</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
    	<th>{{ obj.id }}</th>
    	<th><a href="{% url 'contest_detail' pk=obj.id %}">{{ obj.name }}</a></th>
    	<th>{{ obj.get_division_display }}</th>
    </tr>
    {% empty %}
    <th>No results</th>
   {% endfor %}
  </tbody>
</table>

{% endblock content %}

BitsPlease/templates/notice_list.html
{% extends "base.html" %}

{% block content %}
<br>
<div class="container">

		{% for obj in object_list %}
			<div class="jumbotron">
				<h2>{{ obj.title }}</h2>
				<p>{{ obj.content|safe|linebreaks }}</p>
				<small>{{ obj.date }}</small>
			</div>
		{% empty %}
			<h3>No notices yet</h3>
		{% endfor %}


</div>

{% endblock content %}

BitsPlease/templates/question_detail.html
{% extends "base.html" %}

{% block content %}
	<br>

	<script>
	function myFun(){
	    alert("Make sure you have tried this problem yourself!");
	}
	</script>
	<div class="jumbotron">
		<h2>{{ object.id }}.{{ object.name }}</h2>
		<h5>{% if object.contest %}
			Contest -
			<a href="{% url 'contest_detail' pk=object.contest.id %}">{{ object.contest }}</a>
			|
		{% endif %} Difficulty -  {{ object.get_level_display }}</h5>
		<hr>
		{{ object.description|safe|linebreaks }}

		{% if object.Url1 %}
			<form action="{{ object.Url1 }}" style="display: inline;" target="_blank">
    			<input type="submit" class="btn btn-success" value="One" />
			</form>
		{% endif %}
		{% if object.Url2 %}
			<form action="{{ object.Url2 }}" style="display: inline;" target="_blank">
    			<input type="submit" class="btn btn-success" value="Two" />
			</form>
		{% endif %}
		{% if object.Url3 %}
			<form action="{{ object.Url3 }}" style="display: inline;" target="_blank">
    			<input type="submit" class="btn btn-success" value="Three" />
			</form>
		{% endif %}
		{% if object.Url4 %}
			<form action="{{ object.Url4 }}" style="display: inline;" target="_blank style">
    			<input type="submit" class="btn btn-success" value="Four" />
			</form>
		{% endif %}

		{% if object.Url5 %}
			<form action="{{ object.Url5 }}" style="display: inline;" target="_blank">
    			<input type="submit" class="btn btn-success" value="Five" />
			</form>
		{% endif %}
		<br><br>
		<h5>Compile and test your code <a target="_blank" href="https://ideone.com/">here</a>.</h5>
		{% if object.answer %}

			<form action="{{ object.answer }}" target="_blank">
    			<input onclick = "myFun()" type="submit" class="btn btn-primary" value="Solution" />
			</form>
		{% endif %}
	</div>
{% endblock content %}

BitsPlease/templates/question_list.html
{% extends "base.html" %}

{% block content %}
<br>
<h1>Problems</h1>
<br>
<form class="form-inline" meethod="get">
	<div class="form-group" style="display: inline;">
	    <select class="form-control" style="width:230px;" name='level' >
		  <option disabled selected value> Difficulty </option>
        <option>beginner</option>
	      <option>easy</option>
	      <option>medium</option>
	      <option>hard</option>
	    </select>
    </div>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <div class="form-group">
	    <select class="form-control" style="width:260px;" name="tag" id="exampleFormControlSelect1">
	    <option disabled selected value> Tag </option>
	      {% for tag in tags %}
	      	<option>{{ tag }}</option>
	      {% endfor %}
	    </select>
  	</div>
  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<button type="submit" class="btn btn-success">Filter</button>
</form>
<br>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Difficulty</th>
      <th>Contest</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in object_list %}
    <tr>
    	<th>{{ obj.id }}</th>
    	<th><a href="{% url 'problem_detail' pk=obj.id %}">{{ obj.name }}</a></th>
    	<th>{{ obj.get_level_display }}</th>
    	{% if obj.contest is None %}
    		<th>None</th>
    	{% else %}
    		<th><a href="{% url 'contest_detail' pk=obj.contest.pk %}">{{ obj.contest }}</a></th>
    	{% endif %}

    </tr>
    {% empty %}
    <th>No results</th>
   {% endfor %}
  </tbody>
</table>



{% endblock content %}